---
title       : Forecasting Serious Injuries/Deaths of Drivers in UK (Jan 1969 - Dec 1984)
subtitle    : Naive Forecasting Method
author      : JT Lalis
job         : Researcher
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction

Accident Forecasting is to forecast the safety state based on the available information and observation.

The dataset being used in this app is UKDriverDeaths. It is a time series dataset giving the monthly totals of car drivers in Great Britain killed or seriously injured Jan 1969 to Dec 1984. Compulsory wearing of seat belts was introduced on 31 Jan 1983.

--- .class #id

## The Method
This Shiny app is designed to provide a lightweight yet accurate way of forecasting accidents to help decision making and planning before casualty and loss occur.

The Naive forecasting method was used to develop this Shiny app. For more information about the method, follow the link below:

www.scmfocus.com/demandplanning/2012/03/naive-forecast/

--- .class #id 

## The Shiny App

To start using the Shiny App, click the link below:

https://skycrater.shinyapps.io/DDP_Project/

The sample line graph can be seen below:

```{r, cache=TRUE,echo=FALSE, results='asis'}
library(rCharts)
library(knitr)
data("UKDriverDeaths")

#Pre-process the Data
accident <- function(d){
  ds <- as.data.frame(d)
  colnames(ds) <- "Actual_Deaths"
  ds$Actual_Deaths <- as.numeric(ds$Actual_Deaths)
  
  #Jan 1969 to Dec 1984
  date <- data.frame(m=character(0))
  
  pred <- data.frame(Forecasted_Deaths = numeric(0))
  
  #Building Data Frames for Years and Months
  for(yr in 1969:1984){
    for(mth in 1:12){
      if(mth < 10){
        mYr <- paste("0", as.character(mth), sep="")
        mYr <- paste(yr, mth, "01", sep = "-")
      }else
        mYr <- paste(yr, mth, "01", sep="-")
      date <- rbind(as.matrix(date), as.character(mYr)) 
    }
  }
  date <- as.data.frame(date)
  
  #Building Data Frames for Forecasted Values
  #initialize
  pred <- rbind(as.matrix(pred), c(0))
  
  #start Naive Forecasting
  for(i in 1:nrow(ds)-1){
    pred <- rbind(as.matrix(pred), ds[i,c("Actual_Deaths")])
  }
  
  pred <- as.data.frame(pred)
  
  #Combine Columns
  ds <- cbind(ds, pred)  
  newDS <- cbind(date, ds)
  newDS <- transform(newDS, m=as.character(m))
  
  newDS
}

d <- accident(UKDriverDeaths)

mPlot(x = "m", y = list("Actual_Deaths", "Forecasted_Deaths"), data = d, type = 'Line',
            labels = list('Actual # of Deaths', 'Forecasted # of Deaths'), pointSize = 0)
    

```

--- .class #id 

## Performance Measure

The performance of the forecasting method being used in this Shiny App was measured using symmetric mean absolute percentage error (SMAPE).

For more details about SMAPE, click the link below:
https://en.wikipedia.org/wiki/Symmetric_mean_absolute_percentage_error

Thank you.



